<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-SystemCustomerEngagement.Worker-b741b1d3-a556-4543-9c70-21aad6424c95</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DotNetEnv" Version="3.1.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.8" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.11.2" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.11.2" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.11.0" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" Version="1.11.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SystemCustomerEngagement.Contracts\SystemCustomerEngagement.Contracts.csproj" />
    <ProjectReference Include="..\SystemCustomerEngagement.Infrastructure\app.microservice.customer.engagement.infrastructure.csproj" />
  </ItemGroup>

</Project>
